In [5]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

In [27]:
train_df = pd.read_csv("C:/Users/pc/Documents/My Palettes/train.csv")
test_df = pd.read_csv("C:/Users/pc/Documents/My Palettes/test.csv")

In [29]:
train_df.head(10)

,Item_ID,Store_ID,Item_Store_ID,Item_Weight,Item_Sugar_Content,Item_Visibility,Item_Type,Item_Price,Store_Start_Year,Store_Size,Store_Location_Type,Store_Type,Item_Store_Returns
0,DRA12,BABATUNJI010,DRA12_BABATUNJI010,11.60,Low Sugar,0.068535,Soft Drinks,357.54,2005,NaN,Cluster 3,Grocery Store,709.08
1,DRA12,BABATUNJI013,DRA12_BABATUNJI013,11.60,Low Sugar,0.040912,Soft Drinks,355.79,1994,High,Cluster 3,Supermarket Type1,6381.69
2,DRA12,BABATUNJI017,DRA12_BABATUNJI017,11.60,Low Sugar,0.041178,Soft Drinks,350.79,2014,NaN,Cluster 2,Supermarket Type1,6381.69
3,DRA12,BABATUNJI018,DRA12_BABATUNJI018,11.60,Low Sugar,0.041113,Soft Drinks,355.04,2016,Medium,Cluster 3,Supermarket Type2,2127.23
4,DRA12,BABATUNJI035,DRA12_BABATUNJI035,11.60,Ultra Low Sugar,0.000000,Soft Drinks,354.79,2011,Small,Cluster 2,Supermarket Type1,2481.77
5,DRA12,BABATUNJI045,DRA12_BABATUNJI045,11.60,Low Sugar,0.000000,Soft Drinks,354.04,2009,NaN,Cluster 2,Supermarket Type1,9572.54
6,DRA24,BABATUNJI010,DRA24_BABATUNJI010,19.35,Normal Sugar,0.066832,Soft Drinks,409.72,2005,NaN,Cluster 3,Grocery Store,818.93
7,DRA24,BABATUNJI013,DRA24_BABATUNJI013,19.35,Normal Sugar,0.039895,Soft Drinks,406.22,1994,High,Cluster 3,Supermarket Type1,11055.61
8,DRA24,BABATUNJI017,DRA24_BABATUNJI017,19.35,Normal Sugar,0.040154,Soft Drinks,411.72,2014,NaN,Cluster 2,Supermarket Type1,2866.27
9,DRA24,BABATUNJI019,DRA24_BABATUNJI019,NaN,Normal Sugar,0.069909,Soft Drinks,408.22,1992,Small,Cluster 1,Grocery Store,1228.40

In [31]:
test_df.head(10)

,Item_ID,Store_ID,Item_Store_ID,Item_Weight,Item_Sugar_Content,Item_Visibility,Item_Type,Item_Price,Store_Start_Year,Store_Size,Store_Location_Type,Store_Type
0,DRA59,BABATUNJI010,DRA59_BABATUNJI010,8.270,Normal Sugar,0.214125,Soft Drinks,459.98,2005,NaN,Cluster 3,Grocery Store
1,DRA59,BABATUNJI013,DRA59_BABATUNJI013,8.270,Normal Sugar,0.127821,Soft Drinks,464.98,1994,High,Cluster 3,Supermarket Type1
2,DRB01,BABATUNJI013,DRB01_BABATUNJI013,7.390,Low Sugar,0.082171,Soft Drinks,477.38,1994,High,Cluster 3,Supermarket Type1
3,DRB13,BABATUNJI010,DRB13_BABATUNJI010,6.115,Normal Sugar,0.011791,Soft Drinks,472.63,2005,NaN,Cluster 3,Grocery Store
4,DRB13,BABATUNJI013,DRB13_BABATUNJI013,6.115,Normal Sugar,0.007038,Soft Drinks,473.13,1994,High,Cluster 3,Supermarket Type1
5,DRB25,BABATUNJI017,DRB25_BABATUNJI017,12.300,Low Sugar,0.069853,Soft Drinks,268.73,2014,NaN,Cluster 2,Supermarket Type1
6,DRB25,BABATUNJI027,DRB25_BABATUNJI027,NaN,Low Sugar,0.069123,Soft Drinks,265.23,1992,Medium,Cluster 3,Supermarket Type3
7,DRB25,BABATUNJI035,DRB25_BABATUNJI035,12.300,Low Sugar,0.069447,Soft Drinks,265.98,2011,Small,Cluster 2,Supermarket Type1
8,DRB48,BABATUNJI017,DRB48_BABATUNJI017,16.750,Normal Sugar,0.024994,Soft Drinks,93.71,2014,NaN,Cluster 2,Supermarket Type1
9,DRB48,BABATUNJI027,DRB48_BABATUNJI027,NaN,Normal Sugar,0.024733,Soft Drinks,100.71,1992,Medium,Cluster 3,Supermarket Type3

In [39]:
#Making copies not lose original
train = train_df.copy()
test = test_df.copy()

In [41]:
print("Train shape:", train.shape)
print("Test shape:", test.shape)

Train shape: (4990, 13)
Test shape: (3532, 12)

In [51]:
#Handling missing values

#for Item_Weight
imputer_weight = SimpleImputer(strategy='median')
train['Item_Weight'] = imputer_weight.fit_transform(train[['Item_Weight']])
test['Item_Weight'] = imputer_weight.transform(test[['Item_Weight']])


#for store_size
imputer_store_size = SimpleImputer(strategy='most_frequent')
train['Store_Size'] = imputer_store_size.fit_transform(train[['Store_Size']]).ravel()
test['Store_Size'] = imputer_store_size.transform(test[['Store_Size']]).ravel()

In [53]:
#feature Engineering

#create store_age = 2025-store_start_year
train['Store_Age'] = 2025 - train['Store_Start_Year']
test['Store_Age'] = 2025 - test['Store_Start_Year']

#Drop original_year column
train.drop(columns=['Store_Start_Year'], inplace=True)
test.drop(columns=['Store_Start_Year'], inplace=True)

In [55]:
print(train.head(10))

  Item_ID      Store_ID       Item_Store_ID  Item_Weight Item_Sugar_Content  \
0   DRA12  BABATUNJI010  DRA12_BABATUNJI010        11.60          Low Sugar
1   DRA12  BABATUNJI013  DRA12_BABATUNJI013        11.60          Low Sugar
2   DRA12  BABATUNJI017  DRA12_BABATUNJI017        11.60          Low Sugar
3   DRA12  BABATUNJI018  DRA12_BABATUNJI018        11.60          Low Sugar
4   DRA12  BABATUNJI035  DRA12_BABATUNJI035        11.60    Ultra Low Sugar
5   DRA12  BABATUNJI045  DRA12_BABATUNJI045        11.60          Low Sugar
6   DRA24  BABATUNJI010  DRA24_BABATUNJI010        19.35       Normal Sugar
7   DRA24  BABATUNJI013  DRA24_BABATUNJI013        19.35       Normal Sugar
8   DRA24  BABATUNJI017  DRA24_BABATUNJI017        19.35       Normal Sugar
9   DRA24  BABATUNJI019  DRA24_BABATUNJI019        12.60       Normal Sugar

   Item_Visibility    Item_Type  Item_Price Store_Size Store_Location_Type  \
0         0.068535  Soft Drinks      357.54     Medium           Cluster 3
1         0.040912  Soft Drinks      355.79       High           Cluster 3
2         0.041178  Soft Drinks      350.79     Medium           Cluster 2
3         0.041113  Soft Drinks      355.04     Medium           Cluster 3
4         0.000000  Soft Drinks      354.79      Small           Cluster 2
5         0.000000  Soft Drinks      354.04     Medium           Cluster 2
6         0.066832  Soft Drinks      409.72     Medium           Cluster 3
7         0.039895  Soft Drinks      406.22       High           Cluster 3
8         0.040154  Soft Drinks      411.72     Medium           Cluster 2
9         0.069909  Soft Drinks      408.22      Small           Cluster 1

          Store_Type  Item_Store_Returns  Store_Age
0      Grocery Store              709.08         20
1  Supermarket Type1             6381.69         31
2  Supermarket Type1             6381.69         11
3  Supermarket Type2             2127.23          9
4  Supermarket Type1             2481.77         14
5  Supermarket Type1             9572.54         16
6      Grocery Store              818.93         20
7  Supermarket Type1            11055.61         31
8  Supermarket Type1             2866.27         11
9      Grocery Store             1228.40         33

In [57]:
from sklearn.preprocessing import LabelEncoder

# Create a list of all categorical columns to encode
categorical_cols = ['Item_Sugar_Content', 'Item_Type', 'Store_Size', 'Store_Location_Type', 'Store_Type']

# Initialize encoder
le = LabelEncoder()

# Apply label encoding on both train and test
for col in categorical_cols:
    # Combine values from train + test to avoid mismatch
    all_values = pd.concat([train[col], test[col]], axis=0)
    le.fit(all_values)

    train[col] = le.transform(train[col])
    test[col] = le.transform(test[col])

In [59]:
#Training and prediction of model

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Drop ID columns that won't help the model
drop_cols = ['Item_ID', 'Store_ID', 'Item_Store_ID', 'Item_Store_Returns']
X = train.drop(columns=drop_cols)
y = train['Item_Store_Returns']

# For testing (we drop ID columns but keep them in test set for submission)
X_test = test.drop(columns=['Item_ID', 'Store_ID', 'Item_Store_ID'])

#split the data for validation
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

In [61]:
# Initialize model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit the model
model.fit(X_train, y_train)

# Predict on validation set
y_pred = model.predict(X_valid)

# Calculate RMSE
rmse = np.sqrt(mean_squared_error(y_valid, y_pred))
print("Validation RMSE:", rmse)

Validation RMSE: 3097.8096848626033

In [65]:
# Predict on test set
test_preds = model.predict(X_test)

# Load sample submission
submission = pd.read_csv("C:/Users/pc/Documents/My Palettes/SampleSubmission.csv")

# Fill in predictions
submission['Item_Store_Returns'] = test_preds

# Save to CSV
submission.to_csv("my_submission.csv", index=False)
print("Submission file created: my_submission.csv")

Submission file created: my_submission.csv

In [71]:
my_submission = pd.read_csv("C:/Users/pc/Documents/My Palettes/my_submission.csv")
my_submission

           Item_Store_ID  Item_Store_Returns
0     DRA59_BABATUNJI010           1209.1420
1     DRA59_BABATUNJI013           7132.9819
2     DRB01_BABATUNJI013           7273.7990
3     DRB13_BABATUNJI010           1156.5781
4     DRB13_BABATUNJI013           7720.7513
...                  ...                 ...
3527  NCZ42_BABATUNJI010           1213.0883
3528  NCZ42_BABATUNJI013          10415.5602
3529  NCZ42_BABATUNJI049           8954.7945
3530  NCZ53_BABATUNJI010           1389.4084
3531  NCZ53_BABATUNJI013           7525.9206

[3532 rows x 2 columns]